apiVersion: v1
kind: Service
metadata:
  name: tp-service
  namespace: tp-app
spec:
  selector:
    app: tp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 8000 
